// 2018-02-13 09:55:29.534106 -0800 PST m=+3.734506463
// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots

package feecenter

import (
	"encoding/json"
	"github.com/tencentcloudplatform/tcpicli/core"
)

type DescribeResourceBillsResp struct {
	Code     int    `json:"code"`
	CodeDesc string `json:"codeDesc"`
	Data     struct {
		Amount int `json:"amount"`
		Data   []struct {
			ActionType     string        `json:"actionType"`
			Amount         string        `json:"amount"`
			AppID          string        `json:"appId"`
			CalcUnit       string        `json:"calcUnit"`
			Count          string        `json:"count"`
			EndTime        string        `json:"endTime"`
			ID             string        `json:"id"`
			InstanceID     string        `json:"instanceId"`
			InstanceIDType string        `json:"instanceIdType"`
			ModifyType     string        `json:"modifyType"`
			Month          string        `json:"month"`
			OwnerUin       string        `json:"ownerUin"`
			PayMode        string        `json:"payMode"`
			PayType        string        `json:"payType"`
			PayerMode      string        `json:"payerMode"`
			PayerUin       string        `json:"payerUin"`
			Platform       string        `json:"platform"`
			Price          string        `json:"price"`
			ProductCode    string        `json:"productCode"`
			ProjectID      string        `json:"projectId"`
			Projects       []interface{} `json:"projects"`
			Reduces        []interface{} `json:"reduces"`
			Region         string        `json:"region"`
			ReturnAmount   string        `json:"returnAmount"`
			StartTime      string        `json:"startTime"`
			SubProductCode string        `json:"subProductCode"`
			TimeSpan       string        `json:"timeSpan"`
			TimeUnit       string        `json:"timeUnit"`
			UnitPrice      string        `json:"unitPrice"`
			UsedTimeSpan   string        `json:"usedTimeSpan"`
			ZoneNumber     string        `json:"zoneNumber"`
		} `json:"data"`
		ProductCodeList []string `json:"productCodeList"`
		Total           int      `json:"total"`
	} `json:"data"`
	Message string `json:"message"`
}

// Implement https://cloud.tencent.com/document/api378/10772
func (c *FeecenterClient) DescribeResourceBills(options ...string) (*DescribeResourceBillsResp, error) {
	resp, err := c.DoAction("DescribeResourceBills", options...)
	if err != nil {
		return nil, err
	}
	var s DescribeResourceBillsResp
	err = json.Unmarshal(resp, &s)
	return &s, err
}

func DescribeResourceBills(options ...string) (*DescribeResourceBillsResp, error) {
	return DefaultClient.DescribeResourceBills(options...)
}

func (r *DescribeResourceBillsResp) String(args ...interface{}) (string, error) {
	var b []byte
	var err error
	if len(args) == 0 {
		b, err = json.MarshalIndent(r, "", "  ")
	} else if len(args) == 1 {
		if val, ok := args[0].(string); ok {
			if len(val) == 0 {
				b, err = json.MarshalIndent(r, "", "  ")
			} else {
				b, err = core.FmtOutput(val, r)
			}
		}
	}
	return string(b), err
}
